CSharp MVC Frameworks/Views and Layouts/Chushka/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Chushka.Services.Contracts;
using Chushka.Models.ViewModels.Orders;

namespace Chushka.Controllers
{
    public class OrdersController : BaseController
    {
        private IOrderService ordersService;
        private IProductService productsService;

        public OrdersController(IOrderService ordersService, IProductService productsService)
        {
            this.ordersService = ordersService;
            this.productsService = productsService;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult All()
        {
            var orders = ordersService.GetAllOrders();

            var ordersViewModel = orders.Select(x => new OrderViewModel
                                {
                                    Id = x.Id,
                                    Client = x.Client.UserName,
                                    Product = x.Product.Name,
                                    OrderedOn = x.OrderedOn.ToShortDateString()
                                }).ToArray();

            return View(ordersViewModel);
        }

        [Authorize]
        public IActionResult Create(int id)
        {
            var product = productsService.GetProduct(id);

            if (product == null)
            {
                return this.Redirect("/");
            }

            var user = this.User.Identity.Name;

            ordersService.CreateOrder(product, user);

            return this.Redirect("/");
        }
    }
}

CSharp MVC Frameworks/Views and Layouts/Chushka/Controllers/ProductsController.cs
using Chushka.Models.ViewModels.Products;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Chushka.Services.Contracts;

namespace Chushka.Controllers
{
    public class ProductsController : BaseController
    {
        private IProductService productsService;

        public ProductsController(IProductService productsService)
        {
            this.productsService = productsService;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Create(ProductViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            productsService.Create(model);

            return this.Redirect("/");
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int id)
        {
            var product = productsService.GetProduct(id);

            if (product == null)
            {
                return this.Redirect("/");
            }

            var productViewModel = new ProductViewModel
            {
                Id = product.Id,
                Description = product.Description,
                Name = product.Name,
                Price = product.Price,
                ProductType = product.ProductType.ToString(),
            };

            return this.View(productViewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(ProductViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var product = productsService.GetProduct(model.Id);

            if (product == null)
            {
                return this.Redirect("/");
            }

            productsService.EditProduct(product, model);

            return this.Redirect("/Products/Details?id=" + model.Id);
        }

        [Authorize]
        public IActionResult Details(int id)
        {
            var product = productsService.GetProduct(id);

            if (product == null)
            {
                return this.Redirect("/");
            }

            var productViewModel = new ProductViewModel
            {
                Id = product.Id,
                Description = product.Description,
                Name = product.Name,
                Price = product.Price,
                ProductType = product.ProductType.ToString(),
            };

            return this.View(productViewModel);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            var product = productsService.GetProduct(id);

            if (product == null)
            {
                return this.Redirect("/");
            }

            var productViewModel = new ProductViewModel
            {
                Id = product.Id,
                Description = product.Description,
                Name = product.Name,
                Price = product.Price,
                ProductType = product.ProductType.ToString(),
                DisableValue = "disabled"
            };

            return this.View(productViewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult DeleteAction(int id)
        {
            var product = productsService.GetProduct(id);

            if (product == null)
            {
                return this.Redirect("/");
            }

            productsService.Delete(product);

            return this.Redirect("/");
        }
    }
}

CSharp MVC Frameworks/Views and Layouts/Chushka/Views/Products/Create.cshtml
@{
    ViewData["Title"] = "Create";
}

@model ProductViewModel

<h1 class="text-center">Create Product</h1>
<hr class="bg-secondary half-width" />

<form class="mx-auto half-width" asp-controller="Products" asp-action="Create" method="post">

    <partial name="_InputProductPartial" />

    <partial name="_TypeRadioPartial" />

    <div class="button-holder d-flex justify-content-center">
        <button type="submit" class="btn chushka-bg-color">Create</button>
    </div>
</form>

CSharp MVC Frameworks/Views and Layouts/Chushka/Views/Products/Delete.cshtml
@{
    ViewData["Title"] = "Edit";
}

@model ProductViewModel

<h1 class="text-center">Delete</h1>
<hr class="bg-secondary half-width" />

<form class="mx-auto half-width" asp-controller="Products" asp-action="DeleteAction" asp-route-id="@Model.Id" method="post">

    <partial name="_InputProductPartial" />

    <partial name="_TypeRadioPartial" />

    <div class="button-holder d-flex justify-content-center">
        <button type="submit" class="btn chushka-bg-color">Delete</button>
    </div>
</form>

CSharp MVC Frameworks/Views and Layouts/Chushka/Views/Products/Details.cshtml
@{
    ViewData["Title"] = "Details";
}

@model ProductViewModel

<h1 class="text-center">@Model.Name</h1>
<hr class="hr-2 bg-dark" />
<div class="product-type-holder half-width mx-auto d-flex justify-content-between">
    <h3 class="text-center">Type: @Model.ProductType</h3>
    <h3 class="text-center">Price: $@Model.Price</h3>
</div>
<hr class="hr-2 bg-dark" />
<h3 class="text-center">Description</h3>
<div class="product-description-holder">
    <p class="text-center mt-4">@Model.Description</p>
</div>
<hr class="hr-2 bg-dark" />
<h3 class="text-center">Actions</h3>
<div class="product-action-holder mt-4 d-flex justify-content-around">
    <div class="w-50 d-flex justify-content-around">
        <a asp-controller="Orders" asp-action="Create" asp-route-id="@Model.Id" class="btn chushka-bg-color">Order</a>
        @if (User.IsInRole("Admin"))
        {
            <a asp-controller="Products" asp-action="Edit" asp-route-id="@Model.Id" class="btn chushka-bg-color">Edit</a>
            <a asp-controller="Products" asp-action="Delete" asp-route-id="@Model.Id" class="btn chushka-bg-color">Delete</a>
        }
    </div>
</div>

CSharp MVC Frameworks/Views and Layouts/Chushka/Views/Products/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
}

@model ProductViewModel

<h1 class="text-center">Edit</h1>
<hr class="bg-secondary half-width" />

<form class="mx-auto half-width" asp-controller="Products" asp-action="Edit" asp-route-id="@Model.Id" method="post">

    <partial name="_InputProductPartial" />

    <partial name="_TypeRadioPartial" />

    <div class="button-holder d-flex justify-content-center">
        <button type="submit" class="btn chushka-bg-color">Edit</button>
    </div>
</form>